### ISSUE TITLE
Problem with django-jinja dependencie

### ISSUE THREAD

**Issue by SalahAdDin** [shuup/shuup#1138]
I have this problem with the current `django-jinja` package:
```bash
Performing system checks...

System check identified no issues (0 silenced).
June 26, 2017 - 14:48:46
Django version 1.9.13, using settings 'base.settings.dev'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Internal Server Error: /
Traceback (most recent call last):
  File "/home/salahaddin/Proyectos/E-Commerce/shuup-base/lib/python3.6/site-packages/django/core/handlers/base.py", line 140, in get_response
    response = middleware_method(request, callback, callback_args, callback_kwargs)
  File "/home/salahaddin/Proyectos/E-Commerce/shuup-base/lib/python3.6/site-packages/shuup/front/middleware.py", line 144, in process_view
    maintenance_response = self._get_maintenance_response(request, view_func)
  File "/home/salahaddin/Proyectos/E-Commerce/shuup-base/lib/python3.6/site-packages/shuup/front/middleware.py", line 162, in _get_maintenance_response
    return HttpResponse(loader.render_to_string("shuup/front/maintenance.jinja", request=request), status=503)
  File "/home/salahaddin/Proyectos/E-Commerce/shuup-base/lib/python3.6/site-packages/django/template/loader.py", line 97, in render_to_string
    return template.render(context, request)
  File "/home/salahaddin/Proyectos/E-Commerce/shuup-base/lib/python3.6/site-packages/django_jinja/backend.py", line 83, in render
    context=context)
  File "/home/salahaddin/Proyectos/E-Commerce/shuup-base/lib/python3.6/site-packages/django/dispatch/dispatcher.py", line 192, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/salahaddin/Proyectos/E-Commerce/shuup-base/lib/python3.6/site-packages/debug_toolbar/panels/templates/panel.py", line 87, in _store_template_info
    if (isinstance(template.name, six.string_types) and (
AttributeError: 'Template' object has no attribute 'name'
```

Searching about it i found this [issue](https://github.com/jazzband/django-debug-toolbar/issues/790); seeing in the comments i found a possible [solution](https://github.com/jazzband/django-debug-toolbar/pull/791), but in these comments i read that this problem was fixed in the `2.x.x` `jinja` package version.

So, i think is important update the dependencies in order to avoid errors.

**Comment by tulimaki** [comment]
Thanks for letting us know this.  We will have a look and probably didn't know about since the debug toolbar is not included in default Shuup installation.
