### ISSUE TITLE
Problem appliying shuup_workbench

### ISSUE THREAD

**Issue by SalahAdDin** [shuup/shuup#1140]
Applying workbecnh commands i have this error:
```bash
 python -m shuup_workbench shuup_populate_mock --with-superuser=admin 
[2017-06-26 21:04:12,459] (shuup.api.encoders:INFO): `JSONRenderer.encoder_class` patched.
Traceback (most recent call last):
  File "/home/salahaddin/Proyectos/E-Commerce/shuup-base/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/salahaddin/Proyectos/E-Commerce/shuup-base/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: auth_user

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/salahaddin/Proyectos/E-Commerce/shuup-base/lib/python3.6/site-packages/shuup_workbench/__main__.py", line 25, in <module>
    execute_from_command_line(sys.argv)
  File "/home/salahaddin/Proyectos/E-Commerce/shuup-base/lib/python3.6/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/salahaddin/Proyectos/E-Commerce/shuup-base/lib/python3.6/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/salahaddin/Proyectos/E-Commerce/shuup-base/lib/python3.6/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/salahaddin/Proyectos/E-Commerce/shuup-base/lib/python3.6/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/salahaddin/Proyectos/E-Commerce/shuup-base/lib/python3.6/site-packages/shuup/testing/management/commands/shuup_populate_mock.py", line 30, in handle
    user = get_user_model().objects.filter(**filter_params).first()
  File "/home/salahaddin/Proyectos/E-Commerce/shuup-base/lib/python3.6/site-packages/django/db/models/query.py", line 550, in first
    objects = list((self if self.ordered else self.order_by('pk'))[:1])
  File "/home/salahaddin/Proyectos/E-Commerce/shuup-base/lib/python3.6/site-packages/django/db/models/query.py", line 258, in __iter__
    self._fetch_all()
  File "/home/salahaddin/Proyectos/E-Commerce/shuup-base/lib/python3.6/site-packages/django/db/models/query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/salahaddin/Proyectos/E-Commerce/shuup-base/lib/python3.6/site-packages/django/db/models/query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "/home/salahaddin/Proyectos/E-Commerce/shuup-base/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 848, in execute_sql
    cursor.execute(sql, params)
  File "/home/salahaddin/Proyectos/E-Commerce/shuup-base/lib/python3.6/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/salahaddin/Proyectos/E-Commerce/shuup-base/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/salahaddin/Proyectos/E-Commerce/shuup-base/lib/python3.6/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/salahaddin/Proyectos/E-Commerce/shuup-base/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/salahaddin/Proyectos/E-Commerce/shuup-base/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/salahaddin/Proyectos/E-Commerce/shuup-base/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: auth_user
```

**Comment by SalahAdDin** [comment]
Yep, using `shuup` init.
