### ISSUE TITLE
Error using Shuup workbench for 2.0

### ISSUE THREAD

**Issue by vikrantrathore** [shuup/shuup#1149]
While installing Shuup Workbench it gives following error:
python -m shuup_workbench migrate
"TypeError: startswith first arg must be bytes or a tuple of bytes, not str"

**Comment by Pikkupomo** [comment]
How did you install it?

**Comment by sergey-pshichenko** [comment]
I get the same error.
It looks like it's originating from `shuup_xtheme.0001_initial` migration

`Applying shuup_xtheme.0001_initial...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/commands/migrate.py", line 200, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/executor.py", line 92, in migrate
    self._migrate_all_forwards(plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/executor.py", line 121, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/executor.py", line 198, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/migration.py", line 123, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/operations/models.py", line 59, in database_forwards
    schema_editor.create_model(model)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/schema.py", line 260, in create_model
    self.quote_name(field.column),
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/base/schema.py", line 113, in quote_name
    return self.connection.ops.quote_name(name)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/sqlite3/operations.py", line 153, in quote_name
    if name.startswith('"') and name.endswith('"'):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str`

**Comment by ChenYang-China** [comment]
I got the same error and resolved by changing _db_column=b'data'_  to _db_column='data'_ in the migration file

**Comment by toguko** [comment]
@ChenYang-China, your workaround worked for me.
Can you explain why this was holding the migrations?

I change `db_column=b'data'` to `db_column='data'` in two places at file `/shuup/xtheme/migrations/0001_initial.py`

**Fisrt at line 27**
`('_data', shuup.core.fields.TaggedJSONField(db_column='data', default=dict, verbose_name='internal data')),
`

**And at line 36**
`
('data', shuup.core.fields.TaggedJSONField(db_column='data', default=dict, verbose_name='data')),            ],
`

**Comment by yeisonvargasf** [comment]
Hi, same error here, but I was able to fix the error with @ChenYang-China solution. This error happens because of Python 2.7 migration file (Shuup supports Python 2.7.9+).
