### ISSUE TITLE
shuup migrate error

### ISSUE THREAD

**Issue by userino666** [shuup/shuup#1215]
Getting error TypeError: startswith first arg must be bytes or a tuple of bytes, not str when try to python -m shuup_workbench migrate There is no answer anywhere

```
(venv2) :~/PycharmProjects/untitled1$ python3 -m shuup_workbench migrate [2018-03-24 20:15:50,538] (shuup.api.encoders:INFO): `JSONRenderer.encoder_class` patched.
Operations to perform:
  Apply all migrations: shuup_xtheme, admin, contenttypes, easy_thumbnails, default_tax, shuup_front, sessions, campaigns, shuup_simple_cms, carousel, shuup_testing, shuup_notify, shuup, filer, simple_supplier, auth, registration
Running migrations:
  Rendering model states... DONE
  Applying shuup_xtheme.0001_initial...Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "PycharmProjects/untitled1/venv2/lib/python3.6/site-packages/shuup_workbench/__main__.py", line 25, in <module>
    execute_from_command_line(sys.argv)
  File "PycharmProjects/untitled1/venv2/lib/python3.6/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "PycharmProjects/untitled1/venv2/lib/python3.6/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "PycharmProjects/untitled1/venv2/lib/python3.6/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "PycharmProjects/untitled1/venv2/lib/python3.6/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "PycharmProjects/untitled1/venv2/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 200, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "PycharmProjects/untitled1/venv2/lib/python3.6/site-packages/django/db/migrations/executor.py", line 92, in migrate
    self._migrate_all_forwards(plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "PycharmProjects/untitled1/venv2/lib/python3.6/site-packages/django/db/migrations/executor.py", line 121, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "PycharmProjects/untitled1/venv2/lib/python3.6/site-packages/django/db/migrations/executor.py", line 198, in apply_migration
    state = migration.apply(state, schema_editor)
  File "PycharmProjects/untitled1/venv2/lib/python3.6/site-packages/django/db/migrations/migration.py", line 123, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "PycharmProjects/untitled1/venv2/lib/python3.6/site-packages/django/db/migrations/operations/models.py", line 59, in database_forwards
    schema_editor.create_model(model)
  File "PycharmProjects/untitled1/venv2/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 260, in create_model
    self.quote_name(field.column),
  File "PycharmProjects/untitled1/venv2/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 113, in quote_name
    return self.connection.ops.quote_name(name)
  File "PycharmProjects/untitled1/venv2/lib/python3.6/site-packages/django/db/backends/sqlite3/operations.py", line 153, in quote_name
    if name.startswith('"') and name.endswith('"'):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```

**Comment by chessbr** [comment]
Hi @userino666 ,
I ran the migrations in Python 3.6 and no error raised. Do you have old data to migrate? Do you have the last Shuup version?

**Comment by userino666** [comment]
I've been installing a clean latest version from github.

**Comment by chessbr** [comment]
Are you using master `branch`?

**Comment by userino666** [comment]
yep

**Comment by soulilya** [comment]
Make sure that you install all requirements before migrate in your venv.

**Comment by tulimaki** [comment]
Hey @userino666,

I think here might be the answer for you problem https://github.com/shuup/shuup/issues/1149#issuecomment-336735740.

**Comment by 315xiaoyao** [comment]
I also met this problem. Have you solved it?
