### ISSUE TITLE
Sphinx configuration error due deprecated Django class

### ISSUE THREAD

**Issue by 77cc33** [shuup/shuup#1355]
django.db.models.manager.AbstractManagerDescriptor was depracated https://github.com/django/django/commit/3a47d42fa33012b2156bf04058d933df6b3082d2#diff-53c7979f86107903c879e78e12791851L254

as result sphinx runner can't compile documents

```
Configuration error:
There is a programable error in your configuration file:

Traceback (most recent call last):
  File "C:\Users\user\work\shuup\venv\lib\site-packages\sphinx\config.py", line 161, in __init__
    execfile_(filename, config)
  File "C:\Users\user\work\shuup\venv\lib\site-packages\sphinx\util\pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "conf.py", line 46, in <module>
    patch_for_introspection()
  File "conf.py", line 42, in patch_for_introspection
    import shuup_introspection_helper
  File "C:\Users\user\work\shuup\doc\_ext\shuup_introspection_helper.py", line 47, in <module>
    @PatchFor(django.db.models.manager.AbstractManagerDescriptor, '__get__')
AttributeError: module 'django.db.models.manager' has no attribute 'AbstractManagerDescriptor'
```

**Comment by 77cc33** [comment]
django.db.models.get_models() also deprecated in Django 1.9

```
# Loaded extensions:
Traceback (most recent call last):
  File "C:\Users\user\work\shuup\venv\lib\site-packages\sphinx\cmdline.py", line 295, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "C:\Users\user\work\shuup\venv\lib\site-packages\sphinx\application.py", line 199, in __init__
    self.setup_extension(extension)
  File "C:\Users\user\work\shuup\venv\lib\site-packages\sphinx\application.py", line 523, in setup_extension
    ext_meta = mod.setup(self)
  File "C:\Users\user\work\shuup\doc\_ext\django_sphinx.py", line 13, in setup
    models.get_models()  # Load models
AttributeError: module 'django.db.models' has no attribute 'get_models'
```

**Comment by tulimaki** [comment]
Well it seems these are not the only issues with generating docs. We are looking into this. Thanks!

**Comment by tulimaki** [comment]
Fix for this will likely be merged tomorrow after we have had a bit more time to look into these issues. I was able to reproduce this and those small changes introduced in that PR solved it for me at least.

**Comment by tulimaki** [comment]
Soved.
