### ISSUE TITLE
Telemetry bug

### ISSUE THREAD

**Issue by chessbr** [shuup/shuup#1728]
Check the callstack, looks like something related to the timezone  and DST.
I am using `America/Sao_Paulo` timezone and today is `2019-31-01`
```
Internal Server Error: /admin/
Traceback (most recent call last):
  File "/home/overflow/dev/shuup-cloud/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/overflow/dev/shuup-cloud/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/overflow/dev/shuup-cloud/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/overflow/dev/shuup-cloud/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/overflow/dev/shuup/shuup/admin/utils/urls.py", line 99, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/overflow/dev/shuup-cloud/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/overflow/dev/shuup-cloud/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/overflow/dev/shuup/shuup/admin/views/dashboard.py", line 44, in get
    try_send_telemetry(request)
  File "/home/overflow/dev/shuup/shuup/core/telemetry.py", line 267, in try_send_telemetry
    return _send_telemetry(request=request, max_age_hours=max_age_hours, force_send=force_send)
  File "/home/overflow/dev/shuup/shuup/core/telemetry.py", line 220, in _send_telemetry
    data = get_telemetry_data(request)
  File "/home/overflow/dev/shuup/shuup/core/telemetry.py", line 182, in get_telemetry_data
    "daily_data": get_daily_data(now()),
  File "/home/overflow/dev/shuup/shuup/core/telemetry.py", line 167, in get_daily_data
    data.append(get_daily_data_for_day(day))
  File "/home/overflow/dev/shuup/shuup/core/telemetry.py", line 137, in get_daily_data_for_day
    data["orders"] = Order.objects.filter(order_date_filter).count()
  File "/home/overflow/dev/shuup-cloud/venv/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/overflow/dev/shuup-cloud/venv/lib/python3.6/site-packages/django/db/models/query.py", line 787, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/overflow/dev/shuup-cloud/venv/lib/python3.6/site-packages/django/db/models/query.py", line 805, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/overflow/dev/shuup-cloud/venv/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/overflow/dev/shuup-cloud/venv/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1270, in _add_q
    current_negated, allow_joins, split_subq)
  File "/home/overflow/dev/shuup-cloud/venv/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/home/overflow/dev/shuup-cloud/venv/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1210, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/overflow/dev/shuup-cloud/venv/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1104, in build_lookup
    return final_lookup(lhs, rhs)
  File "/home/overflow/dev/shuup-cloud/venv/lib/python3.6/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/overflow/dev/shuup-cloud/venv/lib/python3.6/site-packages/django/db/models/lookups.py", line 219, in get_prep_lookup
    rhs_value = self.lhs.output_field.get_prep_value(rhs_value)
  File "/home/overflow/dev/shuup-cloud/venv/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 1453, in get_prep_value
    value = timezone.make_aware(value, default_timezone)
  File "/home/overflow/dev/shuup-cloud/venv/lib/python3.6/site-packages/django/utils/timezone.py", line 285, in make_aware
    return timezone.localize(value, is_dst=is_dst)
  File "/home/overflow/dev/shuup-cloud/venv/lib/python3.6/site-packages/pytz/tzinfo.py", line 341, in localize
    raise NonExistentTimeError(dt)
pytz.exceptions.NonExistentTimeError: 2018-11-04 00:00:00
```

**Comment by Pikkupomo** [comment]
http://www.ilian.io/django-pytz-nonexistenttimeerror-and-ambiguoustimeerror/
