### ISSUE TITLE
Module Not Found Error

### ISSUE THREAD

**Issue by mdnur89** [shuup/shuup#1914]
First time using pip to get Shuup, last time i used git but no module not found error. I followed instructions in the docs and merged shuup with an existing project but when i run the migrate command i'm getting an error.

- i replaced the settings file using the one provided in shuup workbench along with urls one too.

- i added the project under installed apps

Full traceback as follows:

`Traceback (most recent call last):
  File "/home/linux0/.virtualenvs/webp_1a_shup/lib/python3.7/site-packages/django/apps/config.py", line 122, in create
    cls = getattr(mod, cls_name)
AttributeError: module 'shuup' has no attribute 'nuttyhoggzweb'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/linux0/.virtualenvs/webp_1a_shup/lib/python3.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/linux0/.virtualenvs/webp_1a_shup/lib/python3.7/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/home/linux0/.virtualenvs/webp_1a_shup/lib/python3.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/linux0/.virtualenvs/webp_1a_shup/lib/python3.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/linux0/.virtualenvs/webp_1a_shup/lib/python3.7/site-packages/django/apps/config.py", line 127, in create
    import_module(entry)
  File "/home/linux0/.virtualenvs/webp_1a_shup/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'shuup.nuttyhoggzweb'`

Please help.Thank you

**Comment by tulimaki** [comment]
Hi @mdnur89,

What is this `shuup.nuttyhoggzweb`? Looks like it is not installed/available. Surely not something that comes from Shuup or workbench settings. Example project template can be found [here](https://github.com/shuup/shuup-project-template).
