### ISSUE TITLE
shuup init not working

### ISSUE THREAD

**Issue by dndoanh** [shuup/shuup#2129]
I got following errors when running shuup init command "python -m shuup_workbench migrate" 
`Creating shop... Default Shop
Creating product type... Standard Product
Creating product type... Digital Product
Creating supplier... Default Supplier
Adding shop for supplier...
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/shuup/shuup-1.10.2b6/shuup_workbench/__main__.py", line 25, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/shuup/shuup-venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/opt/shuup/shuup-venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/shuup/shuup-venv/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/shuup/shuup-venv/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/opt/shuup/shuup-1.10.2b6/shuup/core/management/commands/shuup_init.py", line 103, in handle
    Initializer().run()
  File "/opt/shuup/shuup-1.10.2b6/shuup/core/management/commands/shuup_init.py", line 79, in run
    self.objects[schema["model"]] = self.process_schema(schema)
  File "/opt/shuup/shuup-1.10.2b6/shuup/core/management/commands/shuup_init.py", line 73, in process_schema
    obj.shops.add(Shop.objects.first())
  File "/opt/shuup/shuup-venv/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/shuup/shuup-venv/lib/python3.6/site-packages/django/db/models/query.py", line 567, in first
    objects = list((self if self.ordered else self.order_by('pk'))[:1])
  File "/opt/shuup/shuup-venv/lib/python3.6/site-packages/django/db/models/query.py", line 250, in __iter__
    self._fetch_all()
  File "/opt/shuup/shuup-venv/lib/python3.6/site-packages/parler/managers.py", line 47, in _fetch_all
    super(TranslatableQuerySet, self)._fetch_all()
  File "/opt/shuup/shuup-venv/lib/python3.6/site-packages/django/db/models/query.py", line 1121, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/opt/shuup/shuup-venv/lib/python3.6/site-packages/django/db/models/query.py", line 62, in __iter__
    for row in compiler.results_iter(results):
  File "/opt/shuup/shuup-venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 847, in results_iter
    row = self.apply_converters(row, converters)
  File "/opt/shuup/shuup-venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 832, in apply_converters
    value = converter(value, expression, self.connection, self.query.context)
TypeError: from_db_value() takes 4 positional arguments but 5 were given`

Environments: 
- MacOS 10.13.6 and also Ubuntu 18.04
- Python 3.6 and 3.7 
- Node 8.10.0
- Sqlite 3.19.3 and Mysql 14.14
- Shuup release shuup-1.10.2b6

Please help
Many thanks

**Comment by chessbr** [comment]
Hi @dndoanh ! That is related to a jsonfield issue. Looks like the latest version dropped the support for Django 1.11 version.

To overcome that please install the previous version of it using this command: `pip install jsonfield==2.1.1`

Shuup was already fixed in master branch, but a release is required to be available in PyPi.

**Comment by dndoanh** [comment]
@chessbr it working as you said, tks you so much
