### ISSUE TITLE
Error running python3 -m shuup_workbench migrate on Docker

### ISSUE THREAD

**Issue by ferox** [shuup/shuup#2238]
Error on Step 8/11 : RUN python3 -m shuup_workbench migrate

`System check identified some issues:

WARNINGS:
?: (1_10.W001) The MIDDLEWARE_CLASSES setting is deprecated in Django 1.10 and the MIDDLEWARE setting takes precedence. Since you've set MIDDLEWARE, the value of MIDDLEWARE_CLASSES is ignored.
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/shuup_workbench/__main__.py", line 25, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/commands/migrate.py", line 83, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/loader.py", line 204, in build_graph
    self.load_disk()
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/loader.py", line 115, in load_disk
    migration_module = import_module("%s.%s" % (module_name, migration_name))
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/app/shuup/core/migrations/0071_django2_managers.py", line 8, in <module>
    class Migration(migrations.Migration):
  File "/app/shuup/core/migrations/0071_django2_managers.py", line 18, in Migration
    field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='shuup.Attribute'),
AttributeError: module 'parler.fields' has no attribute 'TranslationsForeignKey`

**AttributeError: module 'parler.fields' has no attribute 'TranslationsForeignKey**

**Comment by anand-jain-official** [comment]
+1. Having the same issue. Is there any solution for this ?

**Comment by ferox** [comment]
> +1. Having the same issue. Is there any solution for this ?

It is working now!!

Have you tried?

Image from node:11.14-slim

Python Version: 3.5.3

**Comment by lucasmoglia** [comment]
Hi! Recently I had an issue related to the same Dockerfile RUN line (python3 -m shuup_workbench migrate)

In this case the error message was "# 12 4.895 ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.7/dist-packages/markupsafe/__init__.py)"

I found that a Jinja package update could be the cause. It works installing the "markupsafe" package. My Dockerfile now looks like:

...
RUN pip3 install -U pip (<-- this line already exist! its just for reference)
RUN pip3 install markupsafe==2.0.1
...

**Comment by ferox** [comment]
Nice. I'll try!

**Comment by officeboyz** [comment]
hi ..
i have same error with branch master : 
```
=> [4/8] WORKDIR /app                                                                                                                                                                                 0.0s
 => [5/8] RUN if [ "0" -eq 1 ]; then pip3 install -r requirements-tests.txt && python3 setup.py build_resources; else pip3 install shuup; fi                                                         461.2s
 => ERROR [6/8] RUN python3 -m shuup_workbench migrate                                                                                                                                                 5.0s
------
 > [6/8] RUN python3 -m shuup_workbench migrate:
#6 4.751 Traceback (most recent call last):
#6 4.751   File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
#6 4.751     "__main__", mod_spec)
#6 4.751   File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
#6 4.751     exec(code, run_globals)
#6 4.751   File "/app/shuup_workbench/__main__.py", line 26, in <module>
#6 4.751     execute_from_command_line(sys.argv)
#6 4.751   File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
#6 4.751     utility.execute()
#6 4.751   File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 357, in execute
#6 4.751     django.setup()
#6 4.751   File "/usr/local/lib/python3.7/dist-packages/django/__init__.py", line 24, in setup
#6 4.751     apps.populate(settings.INSTALLED_APPS)
#6 4.751   File "/usr/local/lib/python3.7/dist-packages/django/apps/registry.py", line 114, in populate
#6 4.751     app_config.import_models()
#6 4.751   File "/usr/local/lib/python3.7/dist-packages/django/apps/config.py", line 211, in import_models
#6 4.751     self.models_module = import_module(models_module_name)
#6 4.751   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
#6 4.751     return _bootstrap._gcd_import(name[level:], package, level)
#6 4.751   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
#6 4.751   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
#6 4.751   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
#6 4.751   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
#6 4.751   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
#6 4.751   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
#6 4.751   File "/app/shuup/core/models/__init__.py", line 10, in <module>
#6 4.751     from ._attributes import Attribute, AttributeChoiceOption, AttributeType, AttributeVisibility
#6 4.751   File "/app/shuup/core/models/_attributes.py", line 30, in <module>
#6 4.751     from shuup.core.templatetags.shuup_common import datetime as format_datetime, number as format_number
#6 4.751   File "/app/shuup/core/templatetags/shuup_common.py", line 29, in <module>
#6 4.751     from jinja2 import Undefined
#6 4.751   File "/usr/local/lib/python3.7/dist-packages/jinja2/__init__.py", line 33, in <module>
#6 4.751     from jinja2.environment import Environment, Template
#6 4.751   File "/usr/local/lib/python3.7/dist-packages/jinja2/environment.py", line 13, in <module>
#6 4.751     from jinja2 import nodes
#6 4.751   File "/usr/local/lib/python3.7/dist-packages/jinja2/nodes.py", line 19, in <module>
#6 4.751     from jinja2.utils import Markup
#6 4.751   File "/usr/local/lib/python3.7/dist-packages/jinja2/utils.py", line 531, in <module>
#6 4.751     from markupsafe import Markup, escape, soft_unicode
#6 4.751 ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.7/dist-packages/markupsafe/__init__.py)
------
failed to solve: process "/bin/sh -c python3 -m shuup_workbench migrate" did not complete successfully: exit code: 1
ubuntu@ip-172-31-19-121:~/shuup$
```
i have update 
markupsafe==2.0.1               # via jinja2
from markupsafe==1.1.1 
change to 2.0 same error
