### ISSUE TITLE
"python manage.py shuup_init" command returns error "ValueError: Error! Invalid theme identifier."

### ISSUE THREAD

**Issue by AGeoCoder** [shuup/shuup#2350]
Hello, I have been trying to follow along with the [Shuup Getting Started guide](https://shuup.readthedocs.io/en/latest/howto/getting_started.html) , but have been running into difficulties for hours. I am new to Django and rusty in Python. I am running WSL 2 Ubuntu v20.04 LTS.

When I run the command "python manage.py shuup_init" I get the error "ValueError: Error! Invalid theme identifier."
The printout from my command is below.

How do I resolve this problem?
Thank you in advance!

---------------------------------------

(shuup-venv) [username]:~/shuupStore/mysite$ python manage.py shuup_init
Creating shop... Default Shop
Creating product type... Standard Product
Creating product type... Digital Product
Creating supplier... Default Supplier
Adding shop for supplier...
Creating sales unit... Pieces
Creating customer tax group... Retail Customers
Creating customer tax group... Company Customers
Creating currency... CAD
Creating order statuses... done.
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/[username]/shuupStore/shuup-venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/[username]/shuupStore/shuup-venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/[username]/shuupStore/shuup-venv/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/[username]/shuupStore/shuup-venv/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/[username]/shuupStore/shuup-venv/lib/python3.8/site-packages/shuup/core/management/commands/shuup_init.py", line 107, in handle
    Initializer().run()
  File "/home/[username]/shuupStore/shuup-venv/lib/python3.8/site-packages/shuup/core/management/commands/shuup_init.py", line 97, in run
    set_current_theme("shuup.themes.classic_gray", Shop.objects.first())
  File "/home/[username]/shuupStore/shuup-venv/lib/python3.8/site-packages/shuup/xtheme/_theme.py", line 484, in set_current_theme
    raise ValueError("Error! Invalid theme identifier.")
ValueError: Error! Invalid theme identifier.

**Comment by FreneticScribbler** [comment]
Just hit and solved this issue myself. You need to have 'shuup.themes.classic_gray' in INSTALLED_APPS to run `shuup_init`. The docs should probably mention this!
