### ISSUE TITLE
"EPROTO: protocol error, symlink" during build_resources

### ISSUE THREAD

**Issue by AmirMeirbekov** [shuup/shuup#538]
Hello

When I run `python setup.py build_resources` I get the following error traceback.
How can I overcome that issue? I am running `shoop` app in virtual machine on Ubuntu.

```
npm WARN peerDependencies The peer dependency file-loader@* included from url-loader will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency babel-core@^5.0.0 included from babel-loader will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency webpack@* included from babel-loader will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency less@^2.3.1 included from less-loader will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN optional dep failed, continuing mime@1.3.4
npm WARN optional dep failed, continuing image-size@0.3.5
npm WARN optional dep failed, continuing errno@0.1.4
npm WARN optional dep failed, continuing mkdirp@0.5.1
npm WARN optional dep failed, continuing request@2.67.0
npm ERR! Linux 3.13.0-83-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "i"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! path ../marked/bin/marked
npm ERR! code EPROTO
npm ERR! errno -71
npm ERR! syscall symlink

npm ERR! EPROTO: protocol error, symlink '../marked/bin/marked' -> '/www/shoop/shoop/admin/node_modules/.bin/marked'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /www/shoop/shoop/admin/npm-debug.log

npm ERR! Linux 3.13.0-83-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
npm ERR! shoop.admin@1.0.0 build: `npm i && gulp bower && gulp build`
npm ERR! Exit status 185
npm ERR!
npm ERR! Failed at the shoop.admin@1.0.0 build script 'npm i && gulp bower && gulp build'.
npm ERR! This is most likely a problem with the shoop.admin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm i && gulp bower && gulp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs shoop.admin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls shoop.admin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /www/shoop/shoop/admin/npm-debug.log
Traceback (most recent call last):
  File "setup.py", line 146, in <module>
    cmdclass=utils.COMMANDS,
  File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/www/shoop/shoop_setup_utils/commands.py", line 77, in run
    resource_building.build_resources(opts)
  File "/www/shoop/shoop_setup_utils/resource_building.py", line 45, in build_resources
    builder.build_all()
  File "/www/shoop/shoop_setup_utils/resource_building.py", line 67, in build_all
    self.build_dirs(package_json_dirs)
  File "/www/shoop/shoop_setup_utils/resource_building.py", line 79, in build_dirs
    self.build(dir)
  File "/www/shoop/shoop_setup_utils/resource_building.py", line 87, in build
    self._run_build(dir)
  File "/www/shoop/shoop_setup_utils/resource_building.py", line 96, in _run_build
    subprocess.check_call(self.command, cwd=dir, env=self.env, shell=shell)
  File "/usr/lib/python3.4/subprocess.py", line 561, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['npm', 'run', 'build']' returned non-zero exit status 1
```

**Comment by suutari-ai** [comment]
Are you building the resources on filesystem that does not support symlinks, e.g. FAT? That won't work, as npm needs a filesystem with symlink support.

**Comment by AmirMeirbekov** [comment]
I building resources within Ubuntu 14 virtual machine (using vagrant and virtual boxes), so not on FAT. The virtual machine is running on host Windows 10 machine (which has NTFS file system)

**Comment by suutari-ai** [comment]
Maybe this will help: http://www.ahtik.com/blog/fixing-your-virtualbox-shared-folder-symlink-error/

Any difference?
