### ISSUE TITLE
Running with gunicorn

### ISSUE THREAD

**Issue by geekrohit** [shuup/shuup#787]
Hi,

I've tried running the project with gunicorn using various switches, wanted to know what was the correct way, since all times it fails to boot worker process.

```
gunicorn shuup_workbench.wsgi:application
```
```
gunicorn shuup_workbench.wsgi
```

I've been able to run it through hendrix, but however, it seemed like it didn't display all the products/details in admin that it'd normally do.

**Comment by chessbr** [comment]
Hi!
Do you have an error log? I run gunicorn without any issues. I can share with you the script I use to run inside a virtualenv:

```
/www/env/bin/gunicorn --workers 3 --reload --bind=unix:/tmp/gunicorn.sock shuup_workbench.wsgi:application
```

**Comment by geekrohit** [comment]
I am getting this when I try to run : 

```
gunicorn --preload shuup_workbench.wsgi:application
Traceback (most recent call last):
  File "/usr/local/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 192, in run
    super(Application, self).run()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 61, in __init__
    self.setup(app)
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 120, in setup
    self.app.wsgi()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/rohit/projekts/shuup/shuup_workbench/wsgi.py", line 20, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python2.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/site-packages/django/apps/config.py", line 123, in create
    import_module(entry)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/rohit/projekts/shuup/shuup/front/apps/registration/__init__.py", line 32, in <module>
    from registration.signals import login_user, user_activated
ImportError: No module named registration.signals
```

**Comment by chessbr** [comment]
Considering this: `ImportError: No module named registration.signals`
Have you installed all Shuup requirements?

**Comment by geekrohit** [comment]
I've done ``` pip install -r requirements-doc.txt ``` .  And isn't registration part of shuup.front.apps ?

**Comment by chessbr** [comment]
According to https://github.com/shuup/shuup/blob/master/doc/getting_started_dev.rst, try this:
`pip install -e .[everything]`

**Comment by geekrohit** [comment]
Ok, I tried doing the pip install in same venv, didn't work, but worked in a fresh one. Thanks!
