### ISSUE TITLE
Product Cross Sell plugin exception

### ISSUE THREAD

**Issue by chessbr** [shuup/shuup#821]
Seems the plugin took a configuration value from a old plugin when I changed the type (from highlight to cross sell) of a plugin in xtheme editor:

```
Traceback (most recent call last):
  File "/srv/www/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/srv/www/env/lib/python3.5/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/srv/www/env/lib/python3.5/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/srv/www/env/lib/python3.5/site-packages/django_jinja/backend.py", line 86, in render
    return self.template.render(context)
  File "/srv/www/src/shuup/shuup/xtheme/engine.py", line 43, in render
    return self.environment.handle_exception(exc_info, True)
  File "/srv/www/env/lib/python3.5/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/www/env/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/srv/www/src/custom-theme/custom_theme/templates/custom_theme/shuup/front/index.jinja", line 1, in top-level template code
    {% extends "shuup/front/base.jinja" %}
  File "/srv/www/src/custom-theme/custom_theme/templates/custom_theme/shuup/front/base.jinja", line 63, in top-level template code
    {% block content %}{% endblock %}
  File "/srv/www/src/custom-theme/custom_theme/templates/custom_theme/shuup/front/index.jinja", line 30, in block "content"
    {% placeholder "front_content" %}
  File "/srv/www/src/shuup/shuup/xtheme/parsing.py", line 228, in _render_placeholder
    global_type=global_type,
  File "/srv/www/src/shuup/shuup/xtheme/rendering.py", line 71, in render_placeholder
    return renderer.render()
  File "/srv/www/src/shuup/shuup/xtheme/rendering.py", line 120, in render
    self._render_layout(write)
  File "/srv/www/src/shuup/shuup/xtheme/rendering.py", line 143, in _render_layout
    self._render_row(write, y, row)
  File "/srv/www/src/shuup/shuup/xtheme/rendering.py", line 163, in _render_row
    self._render_cell(write, x, cell)
  File "/srv/www/src/shuup/shuup/xtheme/rendering.py", line 191, in _render_cell
    content = cell.render(self.context)
  File "/srv/www/src/shuup/shuup/xtheme/layout.py", line 81, in render
    plugin_inst = self.instantiate_plugin()
  File "/srv/www/src/shuup/shuup/xtheme/layout.py", line 67, in instantiate_plugin
    return plugin_class(config=self.config)
  File "/srv/www/src/shuup/shuup/xtheme/plugins/products.py", line 76, in __init__
    type = map_relation_type(relation_type)
  File "/srv/www/src/shuup/shuup/front/template_helpers/product.py", line 94, in map_relation_type
    raise LookupError('Unknown ProductCrossSellType %r' % (relation_type,))
LookupError: Unknown ProductCrossSellType 'random'
[2016-09-23 12:24:23,416] (django.request:ERROR): Internal Server Error: /
Traceback (most recent call last):
  File "/srv/www/src/shuup/shuup/front/template_helpers/product.py", line 92, in map_relation_type
    return getattr(ProductCrossSellType, attr_name)
  File "/usr/lib/python3.5/enum.py", line 274, in __getattr__
    raise AttributeError(name) from None
AttributeError: RANDOM
```

**Comment by tulimaki** [comment]
You can do the change through shell or straight from the database. We will investigate this ASAP. Are you using default plugins under `xtheme.plugins`.

Well it seems that some of the plugins is sharing identifiers.

**Comment by chessbr** [comment]
Yes, I delete the config from database using shell. I used only default plugins. Thanks.
