### ISSUE TITLE
Error in python setup.py build 

### ISSUE THREAD

**Issue by vikrantrathore** [shuup/shuup#920]
There is an error while building shuup development environment.

`python setup.py build_resources`

The error log is:
```

module.js:474
    throw err;
    ^

Error: Cannot find module 'internal/fs'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at evalmachine.<anonymous>:17:20
    at Object.<anonymous> (/Users/vikrantrathore/projects/shuup/shuup/admin/node_modules/gulp/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/Cellar/node/7.1.0/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! shuup.admin@1.0.0 build: `npm i && gulp bower && gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the shuup.admin@1.0.0 build script 'npm i && gulp bower && gulp build'
```

**Comment by gurch101** [comment]
This is likely caused by gulp: https://github.com/gulpjs/gulp/issues/1843

Please try again with the lts version of node (v6.9.1). If you're using `nvm`, run `nvm install --lts`.

**Comment by balsagoth** [comment]
+1

**Comment by strycore** [comment]
This has been confirmed to be a problem with Node 7.x, there is also a similar issue related to npm 4.x. The current workaround until this receives a proper fix is to downgrade to Node 6 and NPM 3.

**Comment by strycore** [comment]
Pull request https://github.com/shuup/shuup/pull/971 should fix this issue.
