### ISSUE TITLE
cannot import name coreapi

### ISSUE THREAD

**Issue by sagoyanfisic** [shuup/shuup#956]
System check identified no issues (0 silenced).
January 03, 2017 - 21:50:55
Django version 1.8.13, using settings 'shuup_workbench.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/home/msalinas/Documentos/shuup/env_data/local/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/home/msalinas/Documentos/shuup/env_data/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 170, in __call__
    self.load_middleware()
  File "/home/msalinas/Documentos/shuup/env_data/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 52, in load_middleware
    mw_instance = mw_class()
  File "/home/msalinas/Documentos/shuup/env_data/local/lib/python2.7/site-packages/django/middleware/locale.py", line 24, in __init__
    for url_pattern in get_resolver(None).url_patterns:
  File "/home/msalinas/Documentos/shuup/env_data/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 401, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/msalinas/Documentos/shuup/env_data/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 395, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/msalinas/Documentos/shuup/shuup/shuup_workbench/urls.py", line 16, in <module>
    url(r'^api/', include('shuup.api.urls')),
  File "/home/msalinas/Documentos/shuup/env_data/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/msalinas/Documentos/shuup/shuup/shuup/api/urls.py", line 15, in <module>
    from .docs import SwaggerSchemaView
  File "/home/msalinas/Documentos/shuup/shuup/shuup/api/docs.py", line 14, in <module>
    from rest_framework.compat import coreapi
ImportError: cannot import name coreapi
[03/Jan/2017 21:51:03] "GET / HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/home/msalinas/Documentos/shuup/env_data/local/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/home/msalinas/Documentos/shuup/env_data/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 170, in __call__
    self.load_middleware()
  File "/home/msalinas/Documentos/shuup/env_data/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 52, in load_middleware
    mw_instance = mw_class()
  File "/home/msalinas/Documentos/shuup/env_data/local/lib/python2.7/site-packages/django/middleware/locale.py", line 24, in __init__
    for url_pattern in get_resolver(None).url_patterns:
  File "/home/msalinas/Documentos/shuup/env_data/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 401, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/msalinas/Documentos/shuup/env_data/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 395, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/msalinas/Documentos/shuup/shuup/shuup_workbench/urls.py", line 16, in <module>
    url(r'^api/', include('shuup.api.urls')),
  File "/home/msalinas/Documentos/shuup/env_data/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/msalinas/Documentos/shuup/shuup/shuup/api/urls.py", line 15, in <module>
    from .docs import SwaggerSchemaView
  File "/home/msalinas/Documentos/shuup/shuup/shuup/api/docs.py", line 14, in <module>
    from rest_framework.compat import coreapi
ImportError: cannot import name coreapi

**Comment by chessbr** [comment]
What version is Django Rest Framework? Consider upgrading to 3.5+ to have access to the `coreapi`.
