### ISSUE TITLE
After Install css Not Loaded on 127.0.0.1/sa

### ISSUE THREAD

**Issue by GembeJr** [shuup/shuup#998]
i got this after fresh install shuup 
`(py-pro) gembe@Gembe-F6E:~/Documents/py-pro/shuup-master$ python -m shuup_workbench runserver
[2017-01-24 19:19:13,801] (shuup.api.encoders:INFO): `JSONRenderer.encoder_class` patched.
[2017-01-24 19:19:21,603] (shuup.api.encoders:INFO): `JSONRenderer.encoder_class` patched.
Performing system checks...

System check identified no issues (0 silenced).
January 24, 2017 - 19:19:26
Django version 1.9.12, using settings 'shuup_workbench.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[24/Jan/2017 19:19:39] "GET /sa/login/ HTTP/1.1" 200 3244
[24/Jan/2017 19:19:40] "GET /static/shuup_admin/css/select2.css?v=1.1.0.post0.dev HTTP/1.1" 404 1712
[24/Jan/2017 19:19:40] "GET /static/shuup_admin/js/base.js?v=1.1.0.post0.dev HTTP/1.1" 200 51022
[24/Jan/2017 19:19:40] "GET /static/shuup_admin/js/vendor.js?v=1.1.0.post0.dev HTTP/1.1" 200 1573309
[24/Jan/2017 19:19:40] "GET /static/shuup_admin/css/base.css?v=1.1.0.post0.dev HTTP/1.1" 404 1703
[24/Jan/2017 19:19:40] "GET /sa/i18n.js?lang=en HTTP/1.1" 200 3217
[24/Jan/2017 19:19:40] "GET /static/shuup_admin/css/select2.css?v=1.1.0.post0.dev HTTP/1.1" 404 1712
[24/Jan/2017 19:19:40] "GET /static/shuup_admin/css/base.css?v=1.1.0.post0.dev HTTP/1.1" 404 1703
[24/Jan/2017 19:19:40] "GET /static/shuup_admin/img/logo_with_text.svg?v=1.1.0.post0.dev HTTP/1.1" 200 14085
[24/Jan/2017 19:19:58] "POST /sa/login/ HTTP/1.1" 302 0
[24/Jan/2017 19:19:58] "GET / HTTP/1.1" 200 2046
[24/Jan/2017 19:20:03] "GET /favicon.ico HTTP/1.1" 301 0
[24/Jan/2017 19:20:03] "GET /favicon.ico/ HTTP/1.1" 404 1733
[24/Jan/2017 19:20:03] "GET /favicon.ico/ HTTP/1.1" 404 1733
[24/Jan/2017 19:20:11] "GET /sa/ HTTP/1.1" 302 0
[24/Jan/2017 19:20:11] "GET /sa/wizard/ HTTP/1.1" 200 70912
[24/Jan/2017 19:20:12] "GET /static/shuup_admin/css/select2.css?v=1.1.0.post0.dev HTTP/1.1" 404 1712
[24/Jan/2017 19:20:12] "GET /static/shuup_admin/js/vendor.js?v=1.1.0.post0.dev HTTP/1.1" 304 0
[24/Jan/2017 19:20:12] "GET /static/shuup_admin/css/base.css?v=1.1.0.post0.dev HTTP/1.1" 404 1703
[24/Jan/2017 19:20:12] "GET /static/xtheme/admin/xtheme_admin.css?v=1.1.0.post0.dev HTTP/1.1" 404 1718
[24/Jan/2017 19:20:12] "GET /static/shuup_admin/js/base.js?v=1.1.0.post0.dev HTTP/1.1" 304 0
[24/Jan/2017 19:20:12] "GET /static/shuup_admin/css/wizard.css?v=1.1.0.post0.dev HTTP/1.1" 404 1709
[24/Jan/2017 19:20:12] "GET /static/shuup_admin/js/wizard.js?v=1.1.0.post0.dev HTTP/1.1" 200 4752
[24/Jan/2017 19:20:12] "GET /sa/i18n.js?lang=en HTTP/1.1" 200 3217
[24/Jan/2017 19:20:12] "GET /static/shuup_admin/img/logo-icon.svg?v=1.1.0.post0.dev HTTP/1.1" 200 1140
[24/Jan/2017 19:20:12] "GET /static/shuup_admin/img/configure.png?v=1.1.0.post0.dev HTTP/1.1" 200 39824
[24/Jan/2017 19:20:12] "GET /static/xtheme/theme.png?v=1.1.0.post0.dev HTTP/1.1" 200 23165
[24/Jan/2017 19:20:12] "GET /static/xtheme/admin/xtheme_admin.css?v=1.1.0.post0.dev HTTP/1.1" 404 1718
[24/Jan/2017 19:20:35] "GET /sa/wizard/ HTTP/1.1" 200 70912
[24/Jan/2017 19:20:36] "GET /static/shuup_admin/css/select2.css?v=1.1.0.post0.dev HTTP/1.1" 404 1712
[24/Jan/2017 19:20:36] "GET /static/shuup_admin/css/base.css?v=1.1.0.post0.dev HTTP/1.1" 404 1703
[24/Jan/2017 19:20:36] "GET /static/xtheme/admin/xtheme_admin.css?v=1.1.0.post0.dev HTTP/1.1" 404 1718
[24/Jan/2017 19:20:36] "GET /static/shuup_admin/js/vendor.js?v=1.1.0.post0.dev HTTP/1.1" 304 0
[24/Jan/2017 19:20:36] "GET /static/shuup_admin/js/base.js?v=1.1.0.post0.dev HTTP/1.1" 304 0
[24/Jan/2017 19:20:36] "GET /static/shuup_admin/css/wizard.css?v=1.1.0.post0.dev HTTP/1.1" 404 1709
[24/Jan/2017 19:20:36] "GET /static/shuup_admin/js/wizard.js?v=1.1.0.post0.dev HTTP/1.1" 304 0
[24/Jan/2017 19:20:36] "GET /sa/i18n.js?lang=en HTTP/1.1" 200 3217
[24/Jan/2017 19:20:36] "GET /static/shuup_admin/img/logo-icon.svg?v=1.1.0.post0.dev HTTP/1.1" 304 0
[24/Jan/2017 19:20:36] "GET /static/xtheme/theme.png?v=1.1.0.post0.dev HTTP/1.1" 304 0
[24/Jan/2017 19:20:36] "GET /static/shuup_admin/img/configure.png?v=1.1.0.post0.dev HTTP/1.1" 304 0
[24/Jan/2017 19:20:36] "GET /static/xtheme/admin/xtheme_admin.css?v=1.1.0.post0.dev HTTP/1.1" 404 1718
[24/Jan/2017 19:21:13] "POST /sa/wizard/ HTTP/1.1" 400 296
[24/Jan/2017 19:21:14] "POST /sa/wizard/ HTTP/1.1" 400 296
`

**Comment by chessbr** [comment]
Hello @GembeJr! Thank you for your report.
Have you run the `python setup.py build_resources`? If so, any error was thrown?
Best!

**Comment by GembeJr** [comment]
Hi @chessbr , yes it was and i was use collecstatic too, but i got that error. 
Now i was delete at all and try fresh install again but i got this error. 
`(py-pro) gembe@Gembe-F6E:~/Documents/py-pro/shuup-master$ python setup.py build_resources
/home/gembe/Documents/py-pro/local/lib/python2.7/site-packages/setuptools/dist.py:332: UserWarning: Normalizing '1.1.0.post0.dev' to '1.1.0.post0.dev0'
  normalized_version,
running build_resources
*** (1/5) Building: ./shuup/front
Using cached result from /home/gembe/.cache/shuup/build_resources/dev/c8/a2db0ce9fa800f736b0c919cdf98f7937e8206
Updating from cache: ./shuup/front/static/shuup/front/css/style.css
Updating from cache: ./shuup/front/static/shuup/front/fonts/FontAwesome.otf
Updating from cache: ./shuup/front/static/shuup/front/fonts/fontawesome-webfont.eot
Updating from cache: ./shuup/front/static/shuup/front/fonts/fontawesome-webfont.svg
Updating from cache: ./shuup/front/static/shuup/front/fonts/fontawesome-webfont.ttf
Updating from cache: ./shuup/front/static/shuup/front/fonts/fontawesome-webfont.woff
Updating from cache: ./shuup/front/static/shuup/front/fonts/fontawesome-webfont.woff2
Updating from cache: ./shuup/front/static/shuup/front/fonts/glyphicons-halflings-regular.eot
Updating from cache: ./shuup/front/static/shuup/front/fonts/glyphicons-halflings-regular.svg
Updating from cache: ./shuup/front/static/shuup/front/fonts/glyphicons-halflings-regular.ttf
Updating from cache: ./shuup/front/static/shuup/front/fonts/glyphicons-halflings-regular.woff
Updating from cache: ./shuup/front/static/shuup/front/fonts/glyphicons-halflings-regular.woff2
Updating from cache: ./shuup/front/static/shuup/front/js/scripts.js
*** (2/5) Building: ./shuup/themes/classic_gray
Using cached result from /home/gembe/.cache/shuup/build_resources/dev/46/7cb653b9efb32c3638b6d8c334fcbbe8d309b2
Updating from cache: ./shuup/themes/classic_gray/static/shuup/classic_gray/pink/style.css
Updating from cache: ./shuup/themes/classic_gray/static/shuup/classic_gray/blue/style.css
*** (3/5) Building: ./shuup/admin

> shuup.admin@1.0.0 build /home/gembe/Documents/py-pro/shuup-master/shuup/admin
> npm i && gulp bower && gulp build

sh: 1: gulp: not found

npm ERR! shuup.admin@1.0.0 build: `npm i && gulp bower && gulp build`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the shuup.admin@1.0.0 build script.
npm ERR! This is most likely a problem with the shuup.admin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm i && gulp bower && gulp build
npm ERR! You can get their info via:
npm ERR!     npm owner ls shuup.admin
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-45-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! cwd /home/gembe/Documents/py-pro/shuup-master/shuup/admin
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/gembe/Documents/py-pro/shuup-master/shuup/admin/npm-debug.log
npm ERR! not ok code 0
Traceback (most recent call last):
  File "setup.py", line 163, in <module>
    cmdclass=utils.COMMANDS,
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/gembe/Documents/py-pro/shuup-master/shuup_setup_utils/commands.py", line 77, in run
    resource_building.build_resources(opts)
  File "/home/gembe/Documents/py-pro/shuup-master/shuup_setup_utils/resource_building.py", line 45, in build_resources
    builder.build_all()
  File "/home/gembe/Documents/py-pro/shuup-master/shuup_setup_utils/resource_building.py", line 67, in build_all
    self.build_dirs(package_json_dirs)
  File "/home/gembe/Documents/py-pro/shuup-master/shuup_setup_utils/resource_building.py", line 79, in build_dirs
    self.build(dir)
  File "/home/gembe/Documents/py-pro/shuup-master/shuup_setup_utils/resource_building.py", line 87, in build
    self._run_build(dir)
  File "/home/gembe/Documents/py-pro/shuup-master/shuup_setup_utils/resource_building.py", line 96, in _run_build
    subprocess.check_call(self.command, cwd=dir, env=self.env, shell=shell)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['npm', 'run', 'build']' returned non-zero exit status 1
` 
Best!

**Comment by chessbr** [comment]
@GembeJr can you provide us you npm version?

**Comment by GembeJr** [comment]
ok, this is my npm version 
`(py-pro) gembe@Gembe-F6E:~/Documents/py-pro/shuup-master$ npm list -g
/usr/lib
└─┬ npm@1.4.28
  ├── abbrev@1.0.5
  ├── ansi@0.3.0
  ├── ansicolors@0.3.2
  ├── ansistyles@0.1.3
  ├── archy@0.0.2
  ├── block-stream@0.0.7
  ├── char-spinner@1.0.1
  ├── child-process-close@0.1.1
  ├── chmodr@0.1.0
  ├── chownr@0.0.1
  ├── cmd-shim@2.0.0 (git://github.com/othiym23/cmd-shim#12de64ca97f45ac600910092f19afacc3d5376dd)
  ├─┬ columnify@1.2.1
  │ ├─┬ strip-ansi@1.0.0
  │ │ └── ansi-regex@0.2.1
  │ └─┬ wcwidth@1.0.0
  │   └─┬ defaults@1.0.0
  │     └── clone@0.1.18
  ├── editor@0.1.0
  ├── fstream@1.0.2
  ├─┬ fstream-npm@1.0.0
  │ └── fstream-ignore@1.0.1
  ├── github-url-from-git@1.4.0
  ├── github-url-from-username-repo@1.0.0
  ├── glob@4.0.5
  ├── graceful-fs@3.0.2
  ├── inflight@1.0.1
  ├── inherits@2.0.1
  ├── ini@1.2.1
  ├─┬ init-package-json@1.0.0
  │ └── promzard@0.2.2
  ├── lockfile@1.0.0
  ├── lru-cache@2.5.0
  ├─┬ minimatch@1.0.0
  │ └── sigmund@1.0.0
  ├─┬ mkdirp@0.5.0
  │ └── minimist@0.0.8
  ├── node-gyp@1.0.1
  ├── nopt@3.0.1
  ├── npm-cache-filename@1.0.1
  ├── npm-install-checks@1.0.2
  ├── npm-registry-client@2.0.7
  ├── npm-user-validate@0.1.0
  ├─┬ npmconf@1.1.8
  │ └─┬ config-chain@1.1.8
  │   └── proto-list@1.2.3
  ├── npmlog@0.1.1
  ├── once@1.3.0
  ├── opener@1.3.0
  ├── osenv@0.1.0
  ├── path-is-inside@1.0.1
  ├─┬ read@1.0.5
  │ └── mute-stream@0.0.4
  ├─┬ read-installed@2.0.5
  │ └── util-extend@1.0.1
  ├─┬ read-package-json@1.2.7
  │ └── normalize-package-data@1.0.1
  ├─┬ request@2.42.0
  │ ├── aws-sign2@0.5.0
  │ ├─┬ bl@0.9.1
  │ │ └─┬ readable-stream@1.0.31
  │ │   ├── core-util-is@1.0.1
  │ │   ├── isarray@0.0.1
  │ │   └── string_decoder@0.10.31
  │ ├── caseless@0.6.0
  │ ├── forever-agent@0.5.2
  │ ├─┬ form-data@0.1.4
  │ │ ├── async@0.9.0
  │ │ ├─┬ combined-stream@0.0.5
  │ │ │ └── delayed-stream@0.0.5
  │ │ └── mime@1.2.11
  │ ├─┬ hawk@1.1.1
  │ │ ├── boom@0.4.2
  │ │ ├── cryptiles@0.2.2
  │ │ ├── hoek@0.9.1
  │ │ └── sntp@0.2.4
  │ ├─┬ http-signature@0.10.0
  │ │ ├── asn1@0.1.11
  │ │ ├── assert-plus@0.1.2
  │ │ └── ctype@0.5.2
  │ ├── json-stringify-safe@5.0.0
  │ ├── mime-types@1.0.2
  │ ├── node-uuid@1.4.1
  │ ├── oauth-sign@0.4.0
  │ ├── qs@1.2.2
  │ ├── stringstream@0.0.4
  │ ├─┬ tough-cookie@0.12.1
  │ │ └── punycode@1.3.1
  │ └── tunnel-agent@0.4.0
  ├── retry@0.6.0
  ├── rimraf@2.2.8
  ├── semver@2.3.0
  ├─┬ sha@1.2.4
  │ └─┬ readable-stream@1.0.27-1
  │   ├── core-util-is@1.0.1
  │   ├── isarray@0.0.1
  │   └── string_decoder@0.10.25-1
  ├── slide@1.1.6
  ├── sorted-object@1.0.0
  ├── tar@1.0.1
  ├── text-table@0.2.0
  ├── uid-number@0.0.5
  └── which@1.0.5
`
so, which npm version should i install to run shuup correctly ?

**Comment by GembeJr** [comment]
sorry i miss this 
`1.4.28
`

**Comment by strycore** [comment]
@GembeJr  the recommended version for npm is 3.10.10 and node 6.9.4 (please note that the latest release of Shuup isn't yet compatible with Node 7 and NPM 4).

**Comment by GembeJr** [comment]
i was using node version v6.9.4 and and npm v. is 3.10.10 but i still got this error 
`*** (3/5) Building: ./shuup/admin

> shuup.admin@1.0.0 build /home/gembe/Documents/py-pro/shuup-master/shuup/admin
> npm i && gulp bower && gulp build

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
sh: 1: gulp: not found

npm ERR! Linux 3.13.0-45-generic
npm ERR! argv "/home/gembe/.nvm/versions/node/v6.9.4/bin/node" "/home/gembe/.nvm/versions/node/v6.9.4/bin/npm" "run" "build"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! shuup.admin@1.0.0 build: `npm i && gulp bower && gulp build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the shuup.admin@1.0.0 build script 'npm i && gulp bower && gulp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the shuup.admin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm i && gulp bower && gulp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs shuup.admin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls shuup.admin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/gembe/Documents/py-pro/shuup-master/shuup/admin/npm-debug.log
Traceback (most recent call last):
  File "setup.py", line 163, in <module>
    cmdclass=utils.COMMANDS,
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/gembe/Documents/py-pro/shuup-master/shuup_setup_utils/commands.py", line 77, in run
    resource_building.build_resources(opts)
  File "/home/gembe/Documents/py-pro/shuup-master/shuup_setup_utils/resource_building.py", line 45, in build_resources
    builder.build_all()
  File "/home/gembe/Documents/py-pro/shuup-master/shuup_setup_utils/resource_building.py", line 67, in build_all
    self.build_dirs(package_json_dirs)
  File "/home/gembe/Documents/py-pro/shuup-master/shuup_setup_utils/resource_building.py", line 79, in build_dirs
    self.build(dir)
  File "/home/gembe/Documents/py-pro/shuup-master/shuup_setup_utils/resource_building.py", line 87, in build
    self._run_build(dir)
  File "/home/gembe/Documents/py-pro/shuup-master/shuup_setup_utils/resource_building.py", line 96, in _run_build
    subprocess.check_call(self.command, cwd=dir, env=self.env, shell=shell)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['npm', 'run', 'build']' returned non-zero exit status 1
`

**Comment by chessbr** [comment]
For some reason it is not installing `gulp` or it is not finding it. As a work around you can install gulp globally `npm install -g gulp`, which I do not recommend.
You can enter in the `shuup/admin` and run `npm i` to install dependencies and see if gulp install successfully or even hard coded `npm install gulp`. Also, you can delete the `shuup/admin/node_modules` folder to remove those installed dependencies.
